Update bsip-0086.md
bitshares/bsips pull request #270
Opened 2020-04-12 14:24 UTC by winston-1984

The end goal is to fund of the BSIP is to fund the committee, not network through the reserve pool.  Updated document to clarify.

2020-04-20 12:14 UTC, sschiessl-bcp requested changes

2020-04-20 12:14 UTC, sschiessl-bcp commented on bsip-0086.md
> +UPDATE: limit `[0,100%]` to `[0,30%]` see: https://github.com/bitshares/bsips/pull/269
The wording change to make it clear it goes to committee seems reasonable.

On the marked change here: https://github.com/bitshares/bsips/issues/194#issuecomment-607404101

2020-04-20 12:15 UTC, sschiessl-bcp commented
Does this need clarification @abitmore ?

2020-04-20 13:09 UTC, abitmore commented
I don't think it's good to change the wording from "to the network" to "to the committee". The final goal is for the network anyway, it's the spirit of the BSIP. Changing it to "for the committee" will make it a much worse taste. Due to technical difficulties we decided that it's best the committee handles the funds for the network, but it's implementation details, the funds are definitely not owned by the committee.

2020-04-20 13:12 UTC, abitmore requested changes
As last message.

2020-05-24 15:50 UTC, shulthz commented
I suggest to pause this BSIP until the resolve the legal risk.

> This BSIP86 has legal risk, i suggest everyone need to consider it very carefully and seek a legal consultancy.

When BSIP86 charges the market fees from the GATEWAY.assets, the BTS system will have joint liability and must be responsible for these GATEWAY.assets, but these GATEWAY.assets were without supervision and control by the BTS system.

Gateway just likes the DApp of BTS, BTS just provides the service and takes the transaction fee of blockchain，DApp do what is not the business of BTS, but when BTS charges the market fees of GATEWAY.assets, the nature of things will become different.

2022-09-18 20:35 UTC, sschiessl-bcp commented
stale

2022-09-18 20:35 UTC, closed without merging